[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "casadi_mpc"
version = "0.0.1"
authors = [
  { name="Filippo Airaldi", email="filippoairaldi@gmail.com" },
]
description = "Model Predictive Control with CasADi"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy >= 1.21.6",
    "casadi >= 3.5.5"
]

[project.urls]
"Homepage" = "https://github.com/FilippoAiraldi/casadi-mpc"
"Bug Tracker" = "https://github.com/FilippoAiraldi/casadi-mpc/issues"
