name: test-coverage

on: [push]

jobs:
  # https://github.com/philschmid/github-actions/blob/master/python/run-unittest-on-pr-open.yaml
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -I numpy>=1.21.6 casadi>=3.5.5 scipy>=1.9.3
      - name: Test with unittest
        run: |
          python -m unittest discover ./tests 'test_*.py'
  
  #coverage:

  
# - name: Code Climate Coverage Action
  #uses: paambaati/codeclimate-action@v3.2.0
   # env:
   #   CC_TEST_REPORTER_ID: <code_climate_reporter_id>
  #with:
  #  coverageCommand: coverage run -m unittest discover
